# Generated by Django 4.2.13 on 2024-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
