# Generated by Django 4.2.13 on 2024-07-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
